### ISSUE TITLE
Create smoother calibration_poses.bag

### ISSUE THREAD

**Issue by mikeferguson** [fetchrobotics/fetch_ros#11]
The current bag file moves the arm around a lot more than it probably needs to. Poses should flow better. At the same time, it would be worth adding some more margin so that a poorly calibrated robot is not at risk of hitting itself.

**Comment by moriarty** [comment]
@narora1

**Comment by erelson** [comment]
Note: Current workaround to issues caused by this is to run calibration at 0.5 or 0.75 velocity.
