### ISSUE TITLE
ROS 2 clarification

### ISSUE THREAD

**Issue by DanielTakeshi** [fetchrobotics/fetch_ros#119]
(I wasn't sure if I should call this a "feature request" so I am just posting as a normal issue.)

Thanks for all the work you've done getting Ubuntu 18.04 support. We're excited to try this out!

Meanwhile, as of today on the master branch, I see this text:

> Kinetic support, has been skipped. 18.04 supports both ROS1 and ROS2, so it was decided that effort will go towards ROS2 support in the future instead of supporting Kinetic.

It mentions ROS1 and ROS2. From my understanding if we use rospy for development, ROS1 requires Python 2 (I assume 2.7) while ROS2 uses Python 3 (I assume 3.5 or higher).

The Fetch Docs for upgrading from 14.04 to 18.04 mention ROS but they don't mention ROS1 or ROS2. I'm assuming you mean ROS1 here, and that the Fetch does not support ROS2 (yet)?

**Comment by erelson** [comment]
Hi Daniel, that is correct. I'll add a note on my next pass at those instructions, though they do currently link to ROS 1 install procedure on the wiki.  @moriarty will know more about future plans.

**Comment by DanielTakeshi** [comment]
Thanks!
