### ISSUE TITLE
fetch_depth_layer can't work in my robot

### ISSUE THREAD

**Issue by chengwei0427** [fetchrobotics/fetch_ros#59]
First of all, thank you for your open source for this project

I am new to ROS, and I want to test the fetch_depth_layer. I download the fetch_depth_layer ,put it in the folder "catkin_ws/src",  and compile the source use "catkin_make -DCATKIN_WITHELIST_PACKAGES="fetch_depth_layer". successful~~
use node pkg `move_base`
here is my `local_costmap_params.yaml`

`local_costmap:  
   global_frame: /odom
   robot_base_frame: /base_link 
   cost_scaling_factor: 0.5  
   inflation_radius: 0.35 #0.45
   update_frequency: 3
   publish_frequency: 3
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.025
   transform_tolerance: 1.0
   map_type: costmap

   plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: fetch_depth_layer, type: "costmap_2d::FetchDepthLayer"}
    #- {name: simple_layer,   type: "simple_layer_namespace::SimpleLayer"} 
    #- {name: grid_layer,   type: "simple_layer_namespace::GridLayer"} 
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"} `

here is my `costmap_common_params.yaml`

`inflation_layer:
  #obstacle_range: 2.5
  #raytrace_range: 3.0
  cost_scaling_factor: 0.5
  inflation_radius: 0.35 #0.45
  robot_radius: 0.2 #0.4

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  max_obstacle_height: 1.7
  min_obstacle_height: 0.01
  observation_sources: scan 
  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 40, inf_is_valid: true}

fetch_depth_layer:
  depth_topic: /camera/depth/image_raw # from kinect
  info_topic: /camera/depth/camera_info  # from kinect
  observations_separation_threshold: 0.2
  ground_orientation_threshold: 1.2
  publish_observations: true
  publish_points: true
  clear_nans: true
  find_ground_plane: false

grid_layer:
  observation_sources: scan
  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}`

run the move_base pkg , I can't get the `clearing_obs` and `marking_obs` in rviz

what's wrong with me? I can't remove the ground use "fetch_depth_layer",can you help me?
Thank you in advance!

**Comment by mikeferguson** [comment]
If you are using the navigation stack with a Fetch or Freight robot, please use the fetch_navigation package configurations. If you have issues with those packages on your Fetch robot, I suggest posting to the fetch-users group or opening a support ticket with Fetch Robotics.

While the licensing certainly allows you to use these packages on other robots, we only officially support the packages on Fetch and Freight robots (which is why we don't have extensive documentation on how to configure these packages on other robots).
