### ISSUE TITLE
Enable Travis & setup ros-industrial/industrial_ci

### ISSUE THREAD

**Issue by moriarty** [fetchrobotics/fetch_ros#85]
This shouldn't be much work. In house we've got TeamCity & [Back-of-House](https://roscon.ros.org/2016/presentations/PhysicalContinuousIntegrationSlides.pdf) but to quickly check community contributions this would be useful.

- [ ] Enable travis-ci: @rctoris https://travis-ci.org/profile/fetchrobotics
      @velveteenrobot has it running on https://github.com/fetchrobotics/fetch_pbd so it's just a matter of toggling a switch
- [ ] Setup ros-industrial/industrial_ci. I'll do this.

**Comment by mikeferguson** [comment]
You could also just turn on PR building on the ROS buildfarm. The turnaround time might be more like an hour, but I doubt that is a big concern

**Comment by moriarty** [comment]
Yep, I've setup the PR building on the ROS buildfarm, travis-ci has been acquired by Idera and I'm not sure how long it will be around :'(

Closing this.
