### ISSUE TITLE
Please consider using a more permissive license than CC-BY-NC-ND for `fetch_description`

### ISSUE THREAD

**Issue by alimuldal** [fetchrobotics/fetch_ros#93]
As far as open source licenses go, CC-BY-NC-ND is about as restrictive as it gets. In particular, the "no derivative works" clause means that it's not possible for others to distribute versions of the URDFs/meshes that have been modified for research purposes, or converted to different formats (e.g. MuJoCo MJCF). Would you consider switching to a more permissive open source license, such as BSD or Apache?

**Comment by erelson** [comment]
We'll look into whether this is the appropriate license for this. Thanks for the heads-up @alimuldal !

@moriarty: https://github.com/fetchrobotics/fetch_ros/blob/melodic-devel/fetch_description/package.xml#L13
https://github.com/fetchrobotics/fetch_ros/commit/505c51bd61b16af2ecd758a17afe5d35bc318bff

**Comment by alimuldal** [comment]
Hi @moriarty, any news on this?

**Comment by moriarty** [comment]
No update yet. Actually I've been on parental leave.

Could you provide a more specific example of your use case?
If we know the use case, we can perhaps find an option... Perhaps dual license allowing research purposes.
@erelson and I can try to find out why the change was made from **Proprietary** to **CC-BY-NC-ND**.

**Comment by alimuldal** [comment]
I'm one of the developers of the DeepMind Control Suite (https://github.com/deepmind/dm_control). I'm interested in potentially using the Fetch meshes and URDFs to create some reinforcement learning environments for research purposes. I'd need to convert the URDFs to MuJoCo's MJCF format, and probably make some tweaks to the model and/or meshes in order to get the desired behaviour in MuJoCo. The "ND" clause means that I would not be able to redistribute the MJCFs or modified meshes. The "NC" clause is also problematic, since I work for Google and everything we do may be considered "commercial" (including research).

**Comment by moriarty** [comment]
Okay thank you for the clarification.

I have spoken with @mmwise and removing the "ND" clause is something that we are considering.

> The "NC" clause is also problematic, since I work for Google and everything we do may be considered "commercial" (including research).

I don't think this is something that we'll remove.

From your description, it sounds like removing the "ND" clause is what is blocking you from going forward and you would need the "NC" clause removed only as a legal precaution in the event that Google decides to commercialize this research?

Would removing the "ND" clause be a reasonable compromise?

**Comment by alimuldal** [comment]
Removing the "no derivatives" clause seems like it would be a helpful change for academic researchers who might want to build on these models, but unfortunately our company policy means that I can't touch any code released under a non-commercial license (for any purpose, including research that's unrelated to any product).

**Comment by moriarty** [comment]
> Removing the "no derivatives" clause seems like it would be a helpful change for academic researchers who might want to build on these models

That sounds good. And I have looked through the Deep Mind Control Suite, it looks very nice.

>  unfortunately our company policy means that I can't touch any code released under a non-commercial license (for any purpose, including research that's unrelated to any product).

That does indeed sound like an unfortunate problem with Google's company policy... 
Is that the same as this document:
1. https://opensource.google.com/docs/thirdparty/licenses/#noncommercial
    https://opensource.google.com/docs/thirdparty/licenses/#ExceptionsTargets

I just did a "Google search" and it seems that Google as a company also releases the Maps Platform for non-commercial use... https://www.google.com/permissions/geoguidelines/ with a link to your sales team for commercial use.

So I think it's reasonable that Fetch continues to do the same, and leaves the NC clause.
I'll bring this up again internally and get back to you.

**Comment by moriarty** [comment]
Just to ping @alimuldal. We're still talking about this internally.

**Comment by mmwise** [comment]
Selected License
Attribution-NonCommercial-ShareAlike 4.0 International

**Comment by moriarty** [comment]
@alimuldal I apologize that this took so long, and hope you're able to share some of your work, despite the **NC** clause still being there. 

> I'm one of the developers of the DeepMind Control Suite (https://github.com/deepmind/dm_control). I'm interested in potentially using the Fetch meshes and URDFs to create some reinforcement learning environments for research purposes. I'd need to convert the URDFs to MuJoCo's MJCF format, and probably make some tweaks to the model and/or meshes in order to get the desired behaviour in MuJoCo. The "ND" clause means that I would not be able to redistribute the MJCFs or modified meshes. The "NC" clause is also problematic, since I work for Google and everything we do may be considered "commercial" (including research).

I'm sure the MuJoCo's would be appreciated by the community
